#!/bin/bash

export REPOSDIR=${BUILD_ROOT}/obs_repo

if [ -d ${BUILD_ROOT}/.pkgs ]; then
	# This step is used when worker is called from obs remote
    
	mkdir -p ${REPOSDIR}/standard/${DEBOOT_ARCH}
    for ORIG in `ls ${BUILD_ROOT}/.pkgs`; do
        DEST=`echo $ORIG | sed -e "s,.deb,-1obs1_${DEBOOT_ARCH}.deb,g"`
        cp ${BUILD_ROOT}/.pkgs/${ORIG} ${REPOSDIR}/standard/${DEBOOT_ARCH}/$DEST
    done
else
	# This step is used on local builds by osc

	mkdir -p ${BUILD_ROOT}/obs_repo/standard/all
	find ${PKG_CACHE_DIR}/*/*/all -type f -name \*.deb -exec ln -sf {} ${BUILD_ROOT}/obs_repo/standard/all \;
	mkdir -p ${BUILD_ROOT}/obs_repo/standard/${DEBOOT_ARCH}
	find ${PKG_CACHE_DIR}/*/*/${DEBOOT_ARCH} -type f -name \*.deb -exec ln -sf {} ${BUILD_ROOT}/obs_repo/standard/${DEBOOT_ARCH} \;
fi

mkdir -p ${REPOSDIR}/dists/obs/main/binary-${DEBOOT_ARCH}
mkdir -p ${REPOSDIR}/cache

# Create apt-ftparchive files
cat > ${REPOSDIR}/apt-ftparchive-obs.conf << EOF
Dir {
  ArchiveDir "${REPOSDIR}";
  CacheDir "${REPOSDIR}/cache";
};

Default {
  Packages::Compress ".";
  Sources::Compress ".";
  Contents::Compress ".";
};

TreeDefault {
  BinCacheDB "packages-\$(SECTION)-\$(ARCH).db";
  Directory "standard";
  Packages "\$(DIST)/\$(SECTION)/binary-\$(ARCH)/Packages";
  SrcDirectory "pool/\$(SECTION)";
  Sources "\$(DIST)/\$(SECTION)/source/Sources";
  Contents "\$(DIST)/Contents-\$(ARCH)";
  };

Tree "dists/obs" {
    Sections "main";
    Architectures "${DEBOOT_ARCH}";
}
EOF

cat > ${REPOSDIR}/obs-release.conf << EOF
APT::FTPArchive::Release::Origin "OBS";
APT::FTPArchive::Release::Label "OBS";
APT::FTPArchive::Release::Suite "obs";
APT::FTPArchive::Release::Codename "obs";
APT::FTPArchive::Release::Architectures "${DEBOOT_ARCH}";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Open Build Server local deb repos";
EOF

apt-ftparchive generate ${REPOSDIR}/apt-ftparchive-obs.conf
apt-ftparchive -c ${REPOSDIR}/obs-release.conf release ${REPOSDIR}/dists/obs/ > ${REPOSDIR}/dists/obs/Release

echo "Done generate repos ..."
